# Generated by Django 3.2.6 on 2021-11-30 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
    ]
