# Generated by Django 3.2.6 on 2021-12-18 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20211215_1721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
