# Generated by Django 3.2.6 on 2021-12-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='media/avatars/avatar_default.png', upload_to='avatars/'),
        ),
    ]
